image: python:3.7

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install --no-deps dicomweb-client
    - pip install -r test-requirements.txt
    - python -m pytest test_imports.py --cov=run
