image: python:3.7

test:
  stage: test
  script:
    - pip install pipenv
    - pip install --no-deps dicomweb-client
    - pipenv install --dev --system
    - python -m pytest test_imports.py --cov=run
