services:
  - shell-runner

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install --no-deps dicomweb-client
    - pip install -r test_requirements.txt
    - pytest test_imports.py --cov=run
